let suggestions = [
    "Dil da dimag",
    "college",
    "Agar Tum Sath Ho",
    "Suna Hai",
    "Duniya",
    "Lagdi Lahore di ",
    "Baarishein",
    "Vaaste",
    "Blank Space",
    "Faded",
    "Perfect",
    "Stay",
];
// let suggestions = [
//     {
//         ids:"1",
//         songNames: `Dil Da Dimaag`,
//         // songArtists:`<div class="subtitle">Sharrry Maan</div>`,
//         // posters: "img/1.jpg",
//     },
//     {
//         ids:"2",
//         songNames: `College`,
//         // songArtists:`<div class="subtitle">Mankirt Aulakh</div>`,
//         // posters: "img/2.jpg",
//     },
//     {
//         ids:"3",
//         songNames: `Agar Tum Sath Ho`,
//         // songArtists:`<div class="subtitle">Tamashaa</div>`,
//         // posters: "img/3.jpg",
//     },
//     {
//         ids:"4",
//         songNames: `Suna Hai`,
//         // songArtists:`<div class="subtitle">Neha Kakker</div>`,
//         // posters: "img/4.jpg",
//     },
//     {
//         ids:"5",
//         songNames: `Duniya`,
//         // songArtists:`<div class="subtitle">Luka Chuppi</div>`,
//         // posters: "img/5.jpg",
//     },
//     {
//         ids:"6",
//         songNames: `Lagdi Lahore Di`,
//         // songArtists:`<div class="subtitle">Street Dancer 3D</div>`,
//         // posters: "img/6.jpg",
//     },
//     {
//         ids:"7",
//         songNames: `Baarishein`,
//         // songArtists:`<div class="subtitle">Atif Aslam</div>`,
//         // posters: "img/7.jpg",
//     },
//     {
//         ids:"8",
//         songNames: `Vaaste`,
//         // songArtists:`<div class="subtitle">Dhvani Bhanushali</div>`,
//         // posters: "img/8.jpg",
//     },
//     {
//         ids:"9",
//         songNames: `Blank space`,
//         // songArtists:`<div class="subtitle">Taylor Swift</div>`,
//         // posters: "img/9.jpg",
//     },
//     {
//         ids:"10",
//         songNames: `Faded`,
//         // songArtists:`<div class="subtitle">Alan Walker</div>`, 
//         // posters: "img/10.jpg",
//     },
//     {
//         ids:"11",
//         songNames: `Perfect`,
//         // songArtists:`<div class="subtitle">Ed Sheeran</div>`,
//         // posters: "img/11.jpg",
//     },
//     {
//         ids:"12",
//         songNames: `Stay`,
//         // songArtists:`<div class="subtitle">Justin Bieber</div>`,
//         // posters: "img/12.jpg",
//     },
// ];
